name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Push to Gandi Remote
        run: git push gandi

      - name: Install SSH Key
        # You may pin to the exact commit or the version.
        # uses: shimataro/ssh-key-action@6f350ca8484d8d55c2e361e74d17e638dabe713a
        uses: shimataro/ssh-key-action@v2.1.0
        with:
          # SSH private key
          key: ${{ secrets.GANDI_SSH_PRIV_KEY }}
          # SSH key file name (default: id_rsa)
          name: id_rsa
          # public keys of SSH servers
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy on Gandi
        run: ssh 25418@git.sd5.gpaas.net deploy tay4rva.com.git main
